document.addEventListener('DOMContentLoaded', () => {
    const chartTypeSelector = document.getElementById('chartTypeSelector');
    const countrySelector = document.getElementById('countrySelector');
    const imageContainer = document.getElementById('imageContainer');

    // 데이터 매핑
    const chartData = {
        gdp: ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
        "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
        "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
        "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
        "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Central African Republic",
        "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Dem. Rep.",
        "Republic of the Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
        "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Swaziland", "Ethiopia",
        "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
        "Greece", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras",
        "Hong Kong SAR, China", "Hungary", "Iceland", "India", "Indonesia",
        "Iran, Islamic Rep.", "Iraq", "Ireland", "Israel", "Italy", "Côte d'Ivoire",
        "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "South Korea",
        "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
        "Liechtenstein", "Lithuania", "Luxembourg", "Macao SAR, China", "Madagascar", "Malawi",
        "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
        "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
        "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
        "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman",
        "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
        "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "Samoa",
        "San Marino", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
        "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Sudan", "Spain", "Sri Lanka", "St. Kitts and Nevis", "St. Lucia",
        "St. Vincent and the Grenadines", "Sudan", "Suriname", "Sweden", "Switzerland",
        "Syrian Arab Republic", "Tajikistan", "Tanzania", "Thailand", "East Timor", "Togo",
        "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
        "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
        "Vanuatu", "Venezuela, RB", "Vietnam", "Yemen, Rep.", "Zambia", "Zimbabwe"],
        governance: ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
        "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
        "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
        "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
        "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Central African Republic",
        "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Dem. Rep.",
        "Republic of the Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
        "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Swaziland", "Ethiopia",
        "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
        "Greece", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras",
        "Hong Kong SAR, China", "Hungary", "Iceland", "India", "Indonesia",
        "Iran, Islamic Rep.", "Iraq", "Ireland", "Israel", "Italy", "Côte d'Ivoire",
        "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "South Korea",
        "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
        "Liechtenstein", "Lithuania", "Luxembourg", "Macao SAR, China", "Madagascar", "Malawi",
        "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
        "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
        "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
        "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman",
        "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
        "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "Samoa",
        "San Marino", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
        "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Sudan", "Spain", "Sri Lanka", "St. Kitts and Nevis", "St. Lucia",
        "St. Vincent and the Grenadines", "Sudan", "Suriname", "Sweden", "Switzerland",
        "Syrian Arab Republic", "Tajikistan", "Tanzania", "Thailand", "East Timor", "Togo",
        "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
        "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
        "Vanuatu", "Venezuela, RB", "Vietnam", "Yemen, Rep.", "Zambia", "Zimbabwe"],
        import: ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda",
        "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain",
        "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
        "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria",
        "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Central African Republic",
        "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Dem. Rep.",
        "Republic of the Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic",
        "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
        "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Swaziland", "Ethiopia",
        "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana",
        "Greece", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras",
        "Hong Kong SAR, China", "Hungary", "Iceland", "India", "Indonesia",
        "Iran, Islamic Rep.", "Iraq", "Ireland", "Israel", "Italy", "Côte d'Ivoire",
        "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "South Korea",
        "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya",
        "Liechtenstein", "Lithuania", "Luxembourg", "Macao SAR, China", "Madagascar", "Malawi",
        "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Mauritania",
        "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro",
        "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
        "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman",
        "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
        "Poland", "Portugal", "Qatar", "Romania", "Russian Federation", "Rwanda", "Samoa",
        "San Marino", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone",
        "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
        "South Sudan", "Spain", "Sri Lanka", "St. Kitts and Nevis", "St. Lucia",
        "St. Vincent and the Grenadines", "Sudan", "Suriname", "Sweden", "Switzerland",
        "Syrian Arab Republic", "Tajikistan", "Tanzania", "Thailand", "East Timor", "Togo",
        "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu",
        "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan",
        "Vanuatu", "Venezuela, RB", "Vietnam", "Yemen, Rep.", "Zambia", "Zimbabwe"],
        top20: ["Category 2", "Category 4", "Category 6", "Category 7", "Category 8", "Category 9", "Category 20"]
    };

    // 이미지 경로 매핑
    const imageMapping = {
		gdp: {
			"Afghanistan": "/Web/web-layout/data/Graphs/GDP Graphs/Afghanistan.png",
			"Albania": "/Web/web-layout/data/Graphs/GDP Graphs/Albania.png",
			"Algeria": "/Web/web-layout/data/Graphs/GDP Graphs/Algeria.png",
			"Andorra": "/Web/web-layout/data/Graphs/GDP Graphs/Andorra.png",
			"Angola": "/Web/web-layout/data/Graphs/GDP Graphs/Angola.png",
			"Antigua and Barbuda": "/Web/web-layout/data/Graphs/GDP Graphs/Antigua and Barbuda.png",
			"Argentina": "/Web/web-layout/data/Graphs/GDP Graphs/Argentina.png",
			"Armenia": "/Web/web-layout/data/Graphs/GDP Graphs/Armenia.png",
			"Australia": "/Web/web-layout/data/Graphs/GDP Graphs/Australia.png",
			"Austria": "/Web/web-layout/data/Graphs/GDP Graphs/Austria.png",
			"Azerbaijan": "/Web/web-layout/data/Graphs/GDP Graphs/Azerbaijan.png",
			"Bahamas": "/Web/web-layout/data/Graphs/GDP Graphs/Bahamas.png",
			"Bahrain": "/Web/web-layout/data/Graphs/GDP Graphs/Bahrain.png",
			"Bangladesh": "/Web/web-layout/data/Graphs/GDP Graphs/Bangladesh.png",
			"Barbados": "/Web/web-layout/data/Graphs/GDP Graphs/Barbados.png",
			"Belarus": "/Web/web-layout/data/Graphs/GDP Graphs/Belarus.png",
			"Belgium": "/Web/web-layout/data/Graphs/GDP Graphs/Belgium.png",
			"Belize": "/Web/web-layout/data/Graphs/GDP Graphs/Belize.png",
			"Benin": "/Web/web-layout/data/Graphs/GDP Graphs/Benin.png",
			"Bhutan": "/Web/web-layout/data/Graphs/GDP Graphs/Bhutan.png",
			"Bolivia": "/Web/web-layout/data/Graphs/GDP Graphs/Bolivia.png",
			"Bosnia and Herzegovina": "/Web/web-layout/data/Graphs/GDP Graphs/Bosnia and Herzegovina.png",
			"Botswana": "/Web/web-layout/data/Graphs/GDP Graphs/Botswana.png",
			"Brazil": "/Web/web-layout/data/Graphs/GDP Graphs/Brazil.png",
			"Brunei": "/Web/web-layout/data/Graphs/GDP Graphs/Brunei.png",
			"Bulgaria": "/Web/web-layout/data/Graphs/GDP Graphs/Bulgaria.png",
			"Burkina Faso": "/Web/web-layout/data/Graphs/GDP Graphs/Burkina Faso.png",
			"Burundi": "/Web/web-layout/data/Graphs/GDP Graphs/Burundi.png",
			"Cambodia": "/Web/web-layout/data/Graphs/GDP Graphs/Cambodia.png",
			"Cameroon": "/Web/web-layout/data/Graphs/GDP Graphs/Cameroon.png",
			"Canada": "/Web/web-layout/data/Graphs/GDP Graphs/Canada.png",
			"Central African Republic": "/Web/web-layout/data/Graphs/GDP Graphs/Central African Republic.png",
			"Chad": "/Web/web-layout/data/Graphs/GDP Graphs/Chad.png",
			"Chile": "/Web/web-layout/data/Graphs/GDP Graphs/Chile.png",
			"China": "/Web/web-layout/data/Graphs/GDP Graphs/China.png",
			"Colombia": "/Web/web-layout/data/Graphs/GDP Graphs/Colombia.png",
			"Comoros": "/Web/web-layout/data/Graphs/GDP Graphs/Comoros.png",
			"Congo, Dem. Rep.": "/Web/web-layout/data/Graphs/GDP Graphs/Congo Dem Rep.png",
			"Republic of the Congo": "/Web/web-layout/data/Graphs/GDP Graphs/Republic of the Congo.png",
			"Costa Rica": "/Web/web-layout/data/Graphs/GDP Graphs/Costa Rica.png",
			"Croatia": "/Web/web-layout/data/Graphs/GDP Graphs/Croatia.png",
			"Cuba": "/Web/web-layout/data/Graphs/GDP Graphs/Cuba.png",
			"Cyprus": "/Web/web-layout/data/Graphs/GDP Graphs/Cyprus.png",
			"Czech Republic": "/Web/web-layout/data/Graphs/GDP Graphs/Czech Republic.png",
			"Denmark": "/Web/web-layout/data/Graphs/GDP Graphs/Denmark.png",
			"Djibouti": "/Web/web-layout/data/Graphs/GDP Graphs/Djibouti.png",
			"Dominica": "/Web/web-layout/data/Graphs/GDP Graphs/Dominica.png",
			"Dominican Republic": "/Web/web-layout/data/Graphs/GDP Graphs/Dominican Republic.png",
			"Ecuador": "/Web/web-layout/data/Graphs/GDP Graphs/Ecuador.png",
			"Egypt": "/Web/web-layout/data/Graphs/GDP Graphs/Egypt.png",
			"El Salvador": "/Web/web-layout/data/Graphs/GDP Graphs/El Salvador.png",
			"Equatorial Guinea": "/Web/web-layout/data/Graphs/GDP Graphs/Equatorial Guinea.png",
			"Eritrea": "/Web/web-layout/data/Graphs/GDP Graphs/Eritrea.png",
			"Estonia": "/Web/web-layout/data/Graphs/GDP Graphs/Estonia.png",
			"Swaziland": "/Web/web-layout/data/Graphs/GDP Graphs/Swaziland.png",
			"Ethiopia": "/Web/web-layout/data/Graphs/GDP Graphs/Ethiopia.png",
			"Fiji": "/Web/web-layout/data/Graphs/GDP Graphs/Fiji.png",
			"Finland": "/Web/web-layout/data/Graphs/GDP Graphs/Finland.png",
			"France": "/Web/web-layout/data/Graphs/GDP Graphs/France.png",
			"Gabon": "/Web/web-layout/data/Graphs/GDP Graphs/Gabon.png",
			"Gambia": "/Web/web-layout/data/Graphs/GDP Graphs/Gambia.png",
			"Georgia": "/Web/web-layout/data/Graphs/GDP Graphs/Georgia.png",
			"Germany": "/Web/web-layout/data/Graphs/GDP Graphs/Germany.png",
			"Ghana": "/Web/web-layout/data/Graphs/GDP Graphs/Ghana.png",
			"Greece": "/Web/web-layout/data/Graphs/GDP Graphs/Greece.png",
			"Guatemala": "/Web/web-layout/data/Graphs/GDP Graphs/Guatemala.png",
			"Guinea": "/Web/web-layout/data/Graphs/GDP Graphs/Guinea.png",
			"Guinea-Bissau": "/Web/web-layout/data/Graphs/GDP Graphs/Guinea Bissau.png",
			"Guyana": "/Web/web-layout/data/Graphs/GDP Graphs/Guyana.png",
			"Haiti": "/Web/web-layout/data/Graphs/GDP Graphs/Haiti.png",
			"Honduras": "/Web/web-layout/data/Graphs/GDP Graphs/Honduras.png",
			"Hong Kong SAR, China": "/Web/web-layout/data/Graphs/GDP Graphs/Hong Kong SAR China.png",
			"Hungary": "/Web/web-layout/data/Graphs/GDP Graphs/Hungary.png",
			"Iceland": "/Web/web-layout/data/Graphs/GDP Graphs/Iceland.png",
			"India": "/Web/web-layout/data/Graphs/GDP Graphs/India.png",
			"Indonesia": "/Web/web-layout/data/Graphs/GDP Graphs/Indonesia.png",
			"Iran, Islamic Rep.": "/Web/web-layout/data/Graphs/GDP Graphs/Iran Islamic Rep.png",
			"Iraq": "/Web/web-layout/data/Graphs/GDP Graphs/Iraq.png",
			"Ireland": "/Web/web-layout/data/Graphs/GDP Graphs/Ireland.png",
			"Israel": "/Web/web-layout/data/Graphs/GDP Graphs/Israel.png",
			"Italy": "/Web/web-layout/data/Graphs/GDP Graphs/Italy.png",
			"Côte d'Ivoire": "/Web/web-layout/data/Graphs/GDP Graphs/Cote d Ivoire.png",
			"Jamaica": "/Web/web-layout/data/Graphs/GDP Graphs/Jamaica.png",
			"Japan": "/Web/web-layout/data/Graphs/GDP Graphs/Japan.png",
			"Jordan": "/Web/web-layout/data/Graphs/GDP Graphs/Jordan.png",
			"Kazakhstan": "/Web/web-layout/data/Graphs/GDP Graphs/Kazakhstan.png",
			"Kenya": "/Web/web-layout/data/Graphs/GDP Graphs/Kenya.png",
			"Kiribati": "/Web/web-layout/data/Graphs/GDP Graphs/Kiribati.png",
			"South Korea": "/Web/web-layout/data/Graphs/GDP Graphs/South Korea.png",
			"Kuwait": "/Web/web-layout/data/Graphs/GDP Graphs/Kuwait.png",
			"Kyrgyzstan": "/Web/web-layout/data/Graphs/GDP Graphs/Kyrgyzstan.png",
			"Laos": "/Web/web-layout/data/Graphs/GDP Graphs/Laos.png",
			"Latvia": "/Web/web-layout/data/Graphs/GDP Graphs/Latvia.png",
			"Lebanon": "/Web/web-layout/data/Graphs/GDP Graphs/Lebanon.png",
			"Lesotho": "/Web/web-layout/data/Graphs/GDP Graphs/Lesotho.png",
			"Liberia": "/Web/web-layout/data/Graphs/GDP Graphs/Liberia.png",
			"Libya": "/Web/web-layout/data/Graphs/GDP Graphs/Libya.png",
			"Liechtenstein": "/Web/web-layout/data/Graphs/GDP Graphs/Liechtenstein.png",
			"Lithuania": "/Web/web-layout/data/Graphs/GDP Graphs/Lithuania.png",
			"Luxembourg": "/Web/web-layout/data/Graphs/GDP Graphs/Luxembourg.png",
			"Macao SAR, China": "/Web/web-layout/data/Graphs/GDP Graphs/Macao SAR China.png",
			"Madagascar": "/Web/web-layout/data/Graphs/GDP Graphs/Madagascar.png",
			"Malawi": "/Web/web-layout/data/Graphs/GDP Graphs/Malawi.png",
			"Malaysia": "/Web/web-layout/data/Graphs/GDP Graphs/Malaysia.png",
			"Maldives": "/Web/web-layout/data/Graphs/GDP Graphs/Maldives.png",
			"Mali": "/Web/web-layout/data/Graphs/GDP Graphs/Mali.png",
			"Malta": "/Web/web-layout/data/Graphs/GDP Graphs/Malta.png",
			"Marshall Islands": "/Web/web-layout/data/Graphs/GDP Graphs/Marshall Islands.png",
			"Mauritania": "/Web/web-layout/data/Graphs/GDP Graphs/Mauritania.png",
			"Mauritius": "/Web/web-layout/data/Graphs/GDP Graphs/Mauritius.png",
			"Mexico": "/Web/web-layout/data/Graphs/GDP Graphs/Mexico.png",
			"Micronesia": "/Web/web-layout/data/Graphs/GDP Graphs/Micronesia.png",
			"Moldova": "/Web/web-layout/data/Graphs/GDP Graphs/Moldova.png",
			"Monaco": "/Web/web-layout/data/Graphs/GDP Graphs/Monaco.png",
			"Mongolia": "/Web/web-layout/data/Graphs/GDP Graphs/Mongolia.png",
			"Montenegro": "/Web/web-layout/data/Graphs/GDP Graphs/Montenegro.png",
			"Morocco": "/Web/web-layout/data/Graphs/GDP Graphs/Morocco.png",
			"Mozambique": "/Web/web-layout/data/Graphs/GDP Graphs/Mozambique.png",
			"Myanmar": "/Web/web-layout/data/Graphs/GDP Graphs/Myanmar.png",
			"Namibia": "/Web/web-layout/data/Graphs/GDP Graphs/Namibia.png",
			"Nauru": "/Web/web-layout/data/Graphs/GDP Graphs/Nauru.png",
			"Nepal": "/Web/web-layout/data/Graphs/GDP Graphs/Nepal.png",
			"Netherlands": "/Web/web-layout/data/Graphs/GDP Graphs/Netherlands.png",
			"New Zealand": "/Web/web-layout/data/Graphs/GDP Graphs/New Zealand.png",
			"Nicaragua": "/Web/web-layout/data/Graphs/GDP Graphs/Nicaragua.png",
			"Niger": "/Web/web-layout/data/Graphs/GDP Graphs/Niger.png",
			"Nigeria": "/Web/web-layout/data/Graphs/GDP Graphs/Nigeria.png",
			"North Macedonia": "/Web/web-layout/data/Graphs/GDP Graphs/North Macedonia.png",
			"Norway": "/Web/web-layout/data/Graphs/GDP Graphs/Norway.png",
			"Oman": "/Web/web-layout/data/Graphs/GDP Graphs/Oman.png",
			"Pakistan": "/Web/web-layout/data/Graphs/GDP Graphs/Pakistan.png",
			"Palau": "/Web/web-layout/data/Graphs/GDP Graphs/Palau.png",
			"Panama": "/Web/web-layout/data/Graphs/GDP Graphs/Panama.png",
			"Papua New Guinea": "/Web/web-layout/data/Graphs/GDP Graphs/Papua New Guinea.png",
			"Paraguay": "/Web/web-layout/data/Graphs/GDP Graphs/Paraguay.png",
			"Peru": "/Web/web-layout/data/Graphs/GDP Graphs/Peru.png",
			"Philippines": "/Web/web-layout/data/Graphs/GDP Graphs/Philippines.png",
			"Poland": "/Web/web-layout/data/Graphs/GDP Graphs/Poland.png",
			"Portugal": "/Web/web-layout/data/Graphs/GDP Graphs/Portugal.png",
			"Qatar": "/Web/web-layout/data/Graphs/GDP Graphs/Qatar.png",
			"Romania": "/Web/web-layout/data/Graphs/GDP Graphs/Romania.png",
			"Russian Federation": "/Web/web-layout/data/Graphs/GDP Graphs/Russian Federation.png",
			"Rwanda": "/Web/web-layout/data/Graphs/GDP Graphs/Rwanda.png",
			"Samoa": "/Web/web-layout/data/Graphs/GDP Graphs/Samoa.png",
			"San Marino": "/Web/web-layout/data/Graphs/GDP Graphs/San Marino.png",
			"Saudi Arabia": "/Web/web-layout/data/Graphs/GDP Graphs/Saudi Arabia.png",
			"Senegal": "/Web/web-layout/data/Graphs/GDP Graphs/Senegal.png",
			"Serbia": "/Web/web-layout/data/Graphs/GDP Graphs/Serbia.png",
			"Seychelles": "/Web/web-layout/data/Graphs/GDP Graphs/Seychelles.png",
			"Sierra Leone": "/Web/web-layout/data/Graphs/GDP Graphs/Sierra Leone.png",
			"Singapore": "/Web/web-layout/data/Graphs/GDP Graphs/Singapore.png",
			"Slovakia": "/Web/web-layout/data/Graphs/GDP Graphs/Slovakia.png",
			"Slovenia": "/Web/web-layout/data/Graphs/GDP Graphs/Slovenia.png",
			"Solomon Islands": "/Web/web-layout/data/Graphs/GDP Graphs/Solomon Islands.png",
			"Somalia": "/Web/web-layout/data/Graphs/GDP Graphs/Somalia.png",
			"South Africa": "/Web/web-layout/data/Graphs/GDP Graphs/South Africa.png",
			"South Sudan": "/Web/web-layout/data/Graphs/GDP Graphs/South Sudan.png",
			"Spain": "/Web/web-layout/data/Graphs/GDP Graphs/Spain.png",
			"Sri Lanka": "/Web/web-layout/data/Graphs/GDP Graphs/Sri Lanka.png",
			"St. Kitts and Nevis": "/Web/web-layout/data/Graphs/GDP Graphs/St Kitts and Nevis.png",
			"St. Lucia": "/Web/web-layout/data/Graphs/GDP Graphs/St Lucia.png",
			"St. Vincent and the Grenadines": "/Web/web-layout/data/Graphs/GDP Graphs/St Vincent and the Grenadines.png",
			"Sudan": "/Web/web-layout/data/Graphs/GDP Graphs/Sudan.png",
			"Suriname": "/Web/web-layout/data/Graphs/GDP Graphs/Suriname.png",
			"Sweden": "/Web/web-layout/data/Graphs/GDP Graphs/Sweden.png",
			"Switzerland": "/Web/web-layout/data/Graphs/GDP Graphs/Switzerland.png",
			"Syrian Arab Republic": "/Web/web-layout/data/Graphs/GDP Graphs/Syrian Arab Republic.png",
			"Tajikistan": "/Web/web-layout/data/Graphs/GDP Graphs/Tajikistan.png",
			"Tanzania": "/Web/web-layout/data/Graphs/GDP Graphs/Tanzania.png",
			"Thailand": "/Web/web-layout/data/Graphs/GDP Graphs/Thailand.png",
			"East Timor": "/Web/web-layout/data/Graphs/GDP Graphs/East Timor.png",
			"Togo": "/Web/web-layout/data/Graphs/GDP Graphs/Togo.png",
			"Tonga": "/Web/web-layout/data/Graphs/GDP Graphs/Tonga.png",
			"Trinidad and Tobago": "/Web/web-layout/data/Graphs/GDP Graphs/Trinidad and Tobago.png",
			"Tunisia": "/Web/web-layout/data/Graphs/GDP Graphs/Tunisia.png",
			"Turkey": "/Web/web-layout/data/Graphs/GDP Graphs/Turkey.png",
			"Turkmenistan": "/Web/web-layout/data/Graphs/GDP Graphs/Turkmenistan.png",
			"Tuvalu": "/Web/web-layout/data/Graphs/GDP Graphs/Tuvalu.png",
			"Uganda": "/Web/web-layout/data/Graphs/GDP Graphs/Uganda.png",
			"Ukraine": "/Web/web-layout/data/Graphs/GDP Graphs/Ukraine.png",
			"United Arab Emirates": "/Web/web-layout/data/Graphs/GDP Graphs/United Arab Emirates.png",
			"United Kingdom": "/Web/web-layout/data/Graphs/GDP Graphs/United Kingdom.png",
			"United States": "/Web/web-layout/data/Graphs/GDP Graphs/United States.png",
			"Uruguay": "/Web/web-layout/data/Graphs/GDP Graphs/Uruguay.png",
			"Uzbekistan": "/Web/web-layout/data/Graphs/GDP Graphs/Uzbekistan.png",
			"Vanuatu": "/Web/web-layout/data/Graphs/GDP Graphs/Vanuatu.png",
			"Venezuela, RB": "/Web/web-layout/data/Graphs/GDP Graphs/Venezuela RB.png",
			"Vietnam": "/Web/web-layout/data/Graphs/GDP Graphs/Vietnam.png",
			"Yemen, Rep.": "/Web/web-layout/data/Graphs/GDP Graphs/Yemen Rep.png",
			"Zambia": "/Web/web-layout/data/Graphs/GDP Graphs/Zambia.png",
			"Zimbabwe": "/Web/web-layout/data/Graphs/GDP Graphs/Zimbabwe.png"
		},
        governance: {
			"Afghanistan": "/Web/web-layout/data/Graphs/Governance Graphs/Afghanistan.png",
			"Albania": "/Web/web-layout/data/Graphs/Governance Graphs/Albania.png",
			"Algeria": "/Web/web-layout/data/Graphs/Governance Graphs/Algeria.png",
			"Andorra": "/Web/web-layout/data/Graphs/Governance Graphs/Andorra.png",
			"Angola": "/Web/web-layout/data/Graphs/Governance Graphs/Angola.png",
			"Antigua and Barbuda": "/Web/web-layout/data/Graphs/Governance Graphs/Antigua and Barbuda.png",
			"Argentina": "/Web/web-layout/data/Graphs/Governance Graphs/Argentina.png",
			"Armenia": "/Web/web-layout/data/Graphs/Governance Graphs/Armenia.png",
			"Australia": "/Web/web-layout/data/Graphs/Governance Graphs/Australia.png",
			"Austria": "/Web/web-layout/data/Graphs/Governance Graphs/Austria.png",
			"Azerbaijan": "/Web/web-layout/data/Graphs/Governance Graphs/Azerbaijan.png",
			"Bahamas": "/Web/web-layout/data/Graphs/Governance Graphs/Bahamas.png",
			"Bahrain": "/Web/web-layout/data/Graphs/Governance Graphs/Bahrain.png",
			"Bangladesh": "/Web/web-layout/data/Graphs/Governance Graphs/Bangladesh.png",
			"Barbados": "/Web/web-layout/data/Graphs/Governance Graphs/Barbados.png",
			"Belarus": "/Web/web-layout/data/Graphs/Governance Graphs/Belarus.png",
			"Belgium": "/Web/web-layout/data/Graphs/Governance Graphs/Belgium.png",
			"Belize": "/Web/web-layout/data/Graphs/Governance Graphs/Belize.png",
			"Benin": "/Web/web-layout/data/Graphs/Governance Graphs/Benin.png",
			"Bhutan": "/Web/web-layout/data/Graphs/Governance Graphs/Bhutan.png",
			"Bolivia": "/Web/web-layout/data/Graphs/Governance Graphs/Bolivia.png",
			"Bosnia and Herzegovina": "/Web/web-layout/data/Graphs/Governance Graphs/Bosnia and Herzegovina.png",
			"Botswana": "/Web/web-layout/data/Graphs/Governance Graphs/Botswana.png",
			"Brazil": "/Web/web-layout/data/Graphs/Governance Graphs/Brazil.png",
			"Brunei": "/Web/web-layout/data/Graphs/Governance Graphs/Brunei.png",
			"Bulgaria": "/Web/web-layout/data/Graphs/Governance Graphs/Bulgaria.png",
			"Burkina Faso": "/Web/web-layout/data/Graphs/Governance Graphs/Burkina Faso.png",
			"Burundi": "/Web/web-layout/data/Graphs/Governance Graphs/Burundi.png",
			"Cambodia": "/Web/web-layout/data/Graphs/Governance Graphs/Cambodia.png",
			"Cameroon": "/Web/web-layout/data/Graphs/Governance Graphs/Cameroon.png",
			"Canada": "/Web/web-layout/data/Graphs/Governance Graphs/Canada.png",
			"Central African Republic": "/Web/web-layout/data/Graphs/Governance Graphs/Central African Republic.png",
			"Chad": "/Web/web-layout/data/Graphs/Governance Graphs/Chad.png",
			"Chile": "/Web/web-layout/data/Graphs/Governance Graphs/Chile.png",
			"China": "/Web/web-layout/data/Graphs/Governance Graphs/China.png",
			"Colombia": "/Web/web-layout/data/Graphs/Governance Graphs/Colombia.png",
			"Comoros": "/Web/web-layout/data/Graphs/Governance Graphs/Comoros.png",
			"Congo, Dem. Rep.": "/Web/web-layout/data/Graphs/Governance Graphs/Congo Dem Rep.png",
			"Republic of the Congo": "/Web/web-layout/data/Graphs/Governance Graphs/Republic of the Congo.png",
			"Costa Rica": "/Web/web-layout/data/Graphs/Governance Graphs/Costa Rica.png",
			"Croatia": "/Web/web-layout/data/Graphs/Governance Graphs/Croatia.png",
			"Cuba": "/Web/web-layout/data/Graphs/Governance Graphs/Cuba.png",
			"Cyprus": "/Web/web-layout/data/Graphs/Governance Graphs/Cyprus.png",
			"Czech Republic": "/Web/web-layout/data/Graphs/Governance Graphs/Czech Republic.png",
			"Denmark": "/Web/web-layout/data/Graphs/Governance Graphs/Denmark.png",
			"Djibouti": "/Web/web-layout/data/Graphs/Governance Graphs/Djibouti.png",
			"Dominica": "/Web/web-layout/data/Graphs/Governance Graphs/Dominica.png",
			"Dominican Republic": "/Web/web-layout/data/Graphs/Governance Graphs/Dominican Republic.png",
			"Ecuador": "/Web/web-layout/data/Graphs/Governance Graphs/Ecuador.png",
			"Egypt": "/Web/web-layout/data/Graphs/Governance Graphs/Egypt.png",
			"El Salvador": "/Web/web-layout/data/Graphs/Governance Graphs/El Salvador.png",
			"Equatorial Guinea": "/Web/web-layout/data/Graphs/Governance Graphs/Equatorial Guinea.png",
			"Eritrea": "/Web/web-layout/data/Graphs/Governance Graphs/Eritrea.png",
			"Estonia": "/Web/web-layout/data/Graphs/Governance Graphs/Estonia.png",
			"Swaziland": "/Web/web-layout/data/Graphs/Governance Graphs/Swaziland.png",
			"Ethiopia": "/Web/web-layout/data/Graphs/Governance Graphs/Ethiopia.png",
			"Fiji": "/Web/web-layout/data/Graphs/Governance Graphs/Fiji.png",
			"Finland": "/Web/web-layout/data/Graphs/Governance Graphs/Finland.png",
			"France": "/Web/web-layout/data/Graphs/Governance Graphs/France.png",
			"Gabon": "/Web/web-layout/data/Graphs/Governance Graphs/Gabon.png",
			"Gambia": "/Web/web-layout/data/Graphs/Governance Graphs/Gambia.png",
			"Georgia": "/Web/web-layout/data/Graphs/Governance Graphs/Georgia.png",
			"Germany": "/Web/web-layout/data/Graphs/Governance Graphs/Germany.png",
			"Ghana": "/Web/web-layout/data/Graphs/Governance Graphs/Ghana.png",
			"Greece": "/Web/web-layout/data/Graphs/Governance Graphs/Greece.png",
			"Guatemala": "/Web/web-layout/data/Graphs/Governance Graphs/Guatemala.png",
			"Guinea": "/Web/web-layout/data/Graphs/Governance Graphs/Guinea.png",
			"Guinea-Bissau": "/Web/web-layout/data/Graphs/Governance Graphs/Guinea Bissau.png",
			"Guyana": "/Web/web-layout/data/Graphs/Governance Graphs/Guyana.png",
			"Haiti": "/Web/web-layout/data/Graphs/Governance Graphs/Haiti.png",
			"Honduras": "/Web/web-layout/data/Graphs/Governance Graphs/Honduras.png",
			"Hong Kong SAR, China": "/Web/web-layout/data/Graphs/Governance Graphs/Hong Kong SAR China.png",
			"Hungary": "/Web/web-layout/data/Graphs/Governance Graphs/Hungary.png",
			"Iceland": "/Web/web-layout/data/Graphs/Governance Graphs/Iceland.png",
			"India": "/Web/web-layout/data/Graphs/Governance Graphs/India.png",
			"Indonesia": "/Web/web-layout/data/Graphs/Governance Graphs/Indonesia.png",
			"Iran, Islamic Rep.": "/Web/web-layout/data/Graphs/Governance Graphs/Iran Islamic Rep.png",
			"Iraq": "/Web/web-layout/data/Graphs/Governance Graphs/Iraq.png",
			"Ireland": "/Web/web-layout/data/Graphs/Governance Graphs/Ireland.png",
			"Israel": "/Web/web-layout/data/Graphs/Governance Graphs/Israel.png",
			"Italy": "/Web/web-layout/data/Graphs/Governance Graphs/Italy.png",
			"Côte d'Ivoire": "/Web/web-layout/data/Graphs/Governance Graphs/Cote d Ivoire.png",
			"Jamaica": "/Web/web-layout/data/Graphs/Governance Graphs/Jamaica.png",
			"Japan": "/Web/web-layout/data/Graphs/Governance Graphs/Japan.png",
			"Jordan": "/Web/web-layout/data/Graphs/Governance Graphs/Jordan.png",
			"Kazakhstan": "/Web/web-layout/data/Graphs/Governance Graphs/Kazakhstan.png",
			"Kenya": "/Web/web-layout/data/Graphs/Governance Graphs/Kenya.png",
			"Kiribati": "/Web/web-layout/data/Graphs/Governance Graphs/Kiribati.png",
			"South Korea": "/Web/web-layout/data/Graphs/Governance Graphs/South Korea.png",
			"Kuwait": "/Web/web-layout/data/Graphs/Governance Graphs/Kuwait.png",
			"Kyrgyzstan": "/Web/web-layout/data/Graphs/Governance Graphs/Kyrgyzstan.png",
			"Laos": "/Web/web-layout/data/Graphs/Governance Graphs/Laos.png",
			"Latvia": "/Web/web-layout/data/Graphs/Governance Graphs/Latvia.png",
			"Lebanon": "/Web/web-layout/data/Graphs/Governance Graphs/Lebanon.png",
			"Lesotho": "/Web/web-layout/data/Graphs/Governance Graphs/Lesotho.png",
			"Liberia": "/Web/web-layout/data/Graphs/Governance Graphs/Liberia.png",
			"Libya": "/Web/web-layout/data/Graphs/Governance Graphs/Libya.png",
			"Liechtenstein": "/Web/web-layout/data/Graphs/Governance Graphs/Liechtenstein.png",
			"Lithuania": "/Web/web-layout/data/Graphs/Governance Graphs/Lithuania.png",
			"Luxembourg": "/Web/web-layout/data/Graphs/Governance Graphs/Luxembourg.png",
			"Macao SAR, China": "/Web/web-layout/data/Graphs/Governance Graphs/Macao SAR China.png",
			"Madagascar": "/Web/web-layout/data/Graphs/Governance Graphs/Madagascar.png",
			"Malawi": "/Web/web-layout/data/Graphs/Governance Graphs/Malawi.png",
			"Malaysia": "/Web/web-layout/data/Graphs/Governance Graphs/Malaysia.png",
			"Maldives": "/Web/web-layout/data/Graphs/Governance Graphs/Maldives.png",
			"Mali": "/Web/web-layout/data/Graphs/Governance Graphs/Mali.png",
			"Malta": "/Web/web-layout/data/Graphs/Governance Graphs/Malta.png",
			"Marshall Islands": "/Web/web-layout/data/Graphs/Governance Graphs/Marshall Islands.png",
			"Mauritania": "/Web/web-layout/data/Graphs/Governance Graphs/Mauritania.png",
			"Mauritius": "/Web/web-layout/data/Graphs/Governance Graphs/Mauritius.png",
			"Mexico": "/Web/web-layout/data/Graphs/Governance Graphs/Mexico.png",
			"Micronesia": "/Web/web-layout/data/Graphs/Governance Graphs/Micronesia.png",
			"Moldova": "/Web/web-layout/data/Graphs/Governance Graphs/Moldova.png",
			"Monaco": "/Web/web-layout/data/Graphs/Governance Graphs/Monaco.png",
			"Mongolia": "/Web/web-layout/data/Graphs/Governance Graphs/Mongolia.png",
			"Montenegro": "/Web/web-layout/data/Graphs/Governance Graphs/Montenegro.png",
			"Morocco": "/Web/web-layout/data/Graphs/Governance Graphs/Morocco.png",
			"Mozambique": "/Web/web-layout/data/Graphs/Governance Graphs/Mozambique.png",
			"Myanmar": "/Web/web-layout/data/Graphs/Governance Graphs/Myanmar.png",
			"Namibia": "/Web/web-layout/data/Graphs/Governance Graphs/Namibia.png",
			"Nauru": "/Web/web-layout/data/Graphs/Governance Graphs/Nauru.png",
			"Nepal": "/Web/web-layout/data/Graphs/Governance Graphs/Nepal.png",
			"Netherlands": "/Web/web-layout/data/Graphs/Governance Graphs/Netherlands.png",
			"New Zealand": "/Web/web-layout/data/Graphs/Governance Graphs/New Zealand.png",
			"Nicaragua": "/Web/web-layout/data/Graphs/Governance Graphs/Nicaragua.png",
			"Niger": "/Web/web-layout/data/Graphs/Governance Graphs/Niger.png",
			"Nigeria": "/Web/web-layout/data/Graphs/Governance Graphs/Nigeria.png",
			"North Macedonia": "/Web/web-layout/data/Graphs/Governance Graphs/North Macedonia.png",
			"Norway": "/Web/web-layout/data/Graphs/Governance Graphs/Norway.png",
			"Oman": "/Web/web-layout/data/Graphs/Governance Graphs/Oman.png",
			"Pakistan": "/Web/web-layout/data/Graphs/Governance Graphs/Pakistan.png",
			"Palau": "/Web/web-layout/data/Graphs/Governance Graphs/Palau.png",
			"Panama": "/Web/web-layout/data/Graphs/Governance Graphs/Panama.png",
			"Papua New Guinea": "/Web/web-layout/data/Graphs/Governance Graphs/Papua New Guinea.png",
			"Paraguay": "/Web/web-layout/data/Graphs/Governance Graphs/Paraguay.png",
			"Peru": "/Web/web-layout/data/Graphs/Governance Graphs/Peru.png",
			"Philippines": "/Web/web-layout/data/Graphs/Governance Graphs/Philippines.png",
			"Poland": "/Web/web-layout/data/Graphs/Governance Graphs/Poland.png",
			"Portugal": "/Web/web-layout/data/Graphs/Governance Graphs/Portugal.png",
			"Qatar": "/Web/web-layout/data/Graphs/Governance Graphs/Qatar.png",
			"Romania": "/Web/web-layout/data/Graphs/Governance Graphs/Romania.png",
			"Russian Federation": "/Web/web-layout/data/Graphs/Governance Graphs/Russian Federation.png",
			"Rwanda": "/Web/web-layout/data/Graphs/Governance Graphs/Rwanda.png",
			"Samoa": "/Web/web-layout/data/Graphs/Governance Graphs/Samoa.png",
			"San Marino": "/Web/web-layout/data/Graphs/Governance Graphs/San Marino.png",
			"Saudi Arabia": "/Web/web-layout/data/Graphs/Governance Graphs/Saudi Arabia.png",
			"Senegal": "/Web/web-layout/data/Graphs/Governance Graphs/Senegal.png",
			"Serbia": "/Web/web-layout/data/Graphs/Governance Graphs/Serbia.png",
			"Seychelles": "/Web/web-layout/data/Graphs/Governance Graphs/Seychelles.png",
			"Sierra Leone": "/Web/web-layout/data/Graphs/Governance Graphs/Sierra Leone.png",
			"Singapore": "/Web/web-layout/data/Graphs/Governance Graphs/Singapore.png",
			"Slovakia": "/Web/web-layout/data/Graphs/Governance Graphs/Slovakia.png",
			"Slovenia": "/Web/web-layout/data/Graphs/Governance Graphs/Slovenia.png",
			"Solomon Islands": "/Web/web-layout/data/Graphs/Governance Graphs/Solomon Islands.png",
			"Somalia": "/Web/web-layout/data/Graphs/Governance Graphs/Somalia.png",
			"South Africa": "/Web/web-layout/data/Graphs/Governance Graphs/South Africa.png",
			"South Sudan": "/Web/web-layout/data/Graphs/Governance Graphs/South Sudan.png",
			"Spain": "/Web/web-layout/data/Graphs/Governance Graphs/Spain.png",
			"Sri Lanka": "/Web/web-layout/data/Graphs/Governance Graphs/Sri Lanka.png",
			"St. Kitts and Nevis": "/Web/web-layout/data/Graphs/Governance Graphs/St Kitts and Nevis.png",
			"St. Lucia": "/Web/web-layout/data/Graphs/Governance Graphs/St Lucia.png",
			"St. Vincent and the Grenadines": "/Web/web-layout/data/Graphs/Governance Graphs/St Vincent and the Grenadines.png",
			"Sudan": "/Web/web-layout/data/Graphs/Governance Graphs/Sudan.png",
			"Suriname": "/Web/web-layout/data/Graphs/Governance Graphs/Suriname.png",
			"Sweden": "/Web/web-layout/data/Graphs/Governance Graphs/Sweden.png",
			"Switzerland": "/Web/web-layout/data/Graphs/Governance Graphs/Switzerland.png",
			"Syrian Arab Republic": "/Web/web-layout/data/Graphs/Governance Graphs/Syrian Arab Republic.png",
			"Tajikistan": "/Web/web-layout/data/Graphs/Governance Graphs/Tajikistan.png",
			"Tanzania": "/Web/web-layout/data/Graphs/Governance Graphs/Tanzania.png",
			"Thailand": "/Web/web-layout/data/Graphs/Governance Graphs/Thailand.png",
			"East Timor": "/Web/web-layout/data/Graphs/Governance Graphs/East Timor.png",
			"Togo": "/Web/web-layout/data/Graphs/Governance Graphs/Togo.png",
			"Tonga": "/Web/web-layout/data/Graphs/Governance Graphs/Tonga.png",
			"Trinidad and Tobago": "/Web/web-layout/data/Graphs/Governance Graphs/Trinidad and Tobago.png",
			"Tunisia": "/Web/web-layout/data/Graphs/Governance Graphs/Tunisia.png",
			"Turkey": "/Web/web-layout/data/Graphs/Governance Graphs/Turkey.png",
			"Turkmenistan": "/Web/web-layout/data/Graphs/Governance Graphs/Turkmenistan.png",
			"Tuvalu": "/Web/web-layout/data/Graphs/Governance Graphs/Tuvalu.png",
			"Uganda": "/Web/web-layout/data/Graphs/Governance Graphs/Uganda.png",
			"Ukraine": "/Web/web-layout/data/Graphs/Governance Graphs/Ukraine.png",
			"United Arab Emirates": "/Web/web-layout/data/Graphs/Governance Graphs/United Arab Emirates.png",
			"United Kingdom": "/Web/web-layout/data/Graphs/Governance Graphs/United Kingdom.png",
			"United States": "/Web/web-layout/data/Graphs/Governance Graphs/United States.png",
			"Uruguay": "/Web/web-layout/data/Graphs/Governance Graphs/Uruguay.png",
			"Uzbekistan": "/Web/web-layout/data/Graphs/Governance Graphs/Uzbekistan.png",
			"Vanuatu": "/Web/web-layout/data/Graphs/Governance Graphs/Vanuatu.png",
			"Venezuela, RB": "/Web/web-layout/data/Graphs/Governance Graphs/Venezuela RB.png",
			"Vietnam": "/Web/web-layout/data/Graphs/Governance Graphs/Vietnam.png",
			"Yemen, Rep.": "/Web/web-layout/data/Graphs/Governance Graphs/Yemen Rep.png",
			"Zambia": "/Web/web-layout/data/Graphs/Governance Graphs/Zambia.png",
			"Zimbabwe": "/Web/web-layout/data/Graphs/Governance Graphs/Zimbabwe.png"
		},
        import: {
			"Afghanistan": "/Web/web-layout/data/Graphs/Import Graphs/Afghanistan.png",
			"Albania": "/Web/web-layout/data/Graphs/Import Graphs/Albania.png",
			"Algeria": "/Web/web-layout/data/Graphs/Import Graphs/Algeria.png",
			"Andorra": "/Web/web-layout/data/Graphs/Import Graphs/Andorra.png",
			"Angola": "/Web/web-layout/data/Graphs/Import Graphs/Angola.png",
			"Antigua and Barbuda": "/Web/web-layout/data/Graphs/Import Graphs/Antigua_and_Barbuda.png",
			"Argentina": "/Web/web-layout/data/Graphs/Import Graphs/Argentina.png",
			"Armenia": "/Web/web-layout/data/Graphs/Import Graphs/Armenia.png",
			"Australia": "/Web/web-layout/data/Graphs/Import Graphs/Australia.png",
			"Austria": "/Web/web-layout/data/Graphs/Import Graphs/Austria.png",
			"Azerbaijan": "/Web/web-layout/data/Graphs/Import Graphs/Azerbaijan.png",
			"Bahamas": "/Web/web-layout/data/Graphs/Import Graphs/Bahamas.png",
			"Bahrain": "/Web/web-layout/data/Graphs/Import Graphs/Bahrain.png",
			"Bangladesh": "/Web/web-layout/data/Graphs/Import Graphs/Bangladesh.png",
			"Barbados": "/Web/web-layout/data/Graphs/Import Graphs/Barbados.png",
			"Belarus": "/Web/web-layout/data/Graphs/Import Graphs/Belarus.png",
			"Belgium": "/Web/web-layout/data/Graphs/Import Graphs/Belgium.png",
			"Belize": "/Web/web-layout/data/Graphs/Import Graphs/Belize.png",
			"Benin": "/Web/web-layout/data/Graphs/Import Graphs/Benin.png",
			"Bhutan": "/Web/web-layout/data/Graphs/Import Graphs/Bhutan.png",
			"Bolivia": "/Web/web-layout/data/Graphs/Import Graphs/Bolivia.png",
			"Bosnia and Herzegovina": "/Web/web-layout/data/Graphs/Import Graphs/Bosnia_and_Herzegovina.png",
			"Botswana": "/Web/web-layout/data/Graphs/Import Graphs/Botswana.png",
			"Brazil": "/Web/web-layout/data/Graphs/Import Graphs/Brazil.png",
			"Brunei": "/Web/web-layout/data/Graphs/Import Graphs/Brunei.png",
			"Bulgaria": "/Web/web-layout/data/Graphs/Import Graphs/Bulgaria.png",
			"Burkina Faso": "/Web/web-layout/data/Graphs/Import Graphs/Burkina_Faso.png",
			"Burundi": "/Web/web-layout/data/Graphs/Import Graphs/Burundi.png",
			"Cambodia": "/Web/web-layout/data/Graphs/Import Graphs/Cambodia.png",
			"Cameroon": "/Web/web-layout/data/Graphs/Import Graphs/Cameroon.png",
			"Canada": "/Web/web-layout/data/Graphs/Import Graphs/Canada.png",
			"Central African Republic": "/Web/web-layout/data/Graphs/Import Graphs/Central_African_Republic.png",
			"Chad": "/Web/web-layout/data/Graphs/Import Graphs/Chad.png",
			"Chile": "/Web/web-layout/data/Graphs/Import Graphs/Chile.png",
			"China": "/Web/web-layout/data/Graphs/Import Graphs/China.png",
			"Colombia": "/Web/web-layout/data/Graphs/Import Graphs/Colombia.png",
			"Comoros": "/Web/web-layout/data/Graphs/Import Graphs/Comoros.png",
			"Congo, Dem. Rep.": "/Web/web-layout/data/Graphs/Import Graphs/Congo_Dem_Rep.png",
			"Republic of the Congo": "/Web/web-layout/data/Graphs/Import Graphs/Republic_of_the_Congo.png",
			"Costa Rica": "/Web/web-layout/data/Graphs/Import Graphs/Costa_Rica.png",
			"Croatia": "/Web/web-layout/data/Graphs/Import Graphs/Croatia.png",
			"Cuba": "/Web/web-layout/data/Graphs/Import Graphs/Cuba.png",
			"Cyprus": "/Web/web-layout/data/Graphs/Import Graphs/Cyprus.png",
			"Czech Republic": "/Web/web-layout/data/Graphs/Import Graphs/Czech_Republic.png",
			"Denmark": "/Web/web-layout/data/Graphs/Import Graphs/Denmark.png",
			"Djibouti": "/Web/web-layout/data/Graphs/Import Graphs/Djibouti.png",
			"Dominica": "/Web/web-layout/data/Graphs/Import Graphs/Dominica.png",
			"Dominican Republic": "/Web/web-layout/data/Graphs/Import Graphs/Dominican_Republic.png",
			"Ecuador": "/Web/web-layout/data/Graphs/Import Graphs/Ecuador.png",
			"Egypt": "/Web/web-layout/data/Graphs/Import Graphs/Egypt.png",
			"El Salvador": "/Web/web-layout/data/Graphs/Import Graphs/El_Salvador.png",
			"Equatorial Guinea": "/Web/web-layout/data/Graphs/Import Graphs/Equatorial_Guinea.png",
			"Eritrea": "/Web/web-layout/data/Graphs/Import Graphs/Eritrea.png",
			"Estonia": "/Web/web-layout/data/Graphs/Import Graphs/Estonia.png",
			"Swaziland": "/Web/web-layout/data/Graphs/Import Graphs/Swaziland.png",
			"Ethiopia": "/Web/web-layout/data/Graphs/Import Graphs/Ethiopia.png",
			"Fiji": "/Web/web-layout/data/Graphs/Import Graphs/Fiji.png",
			"Finland": "/Web/web-layout/data/Graphs/Import Graphs/Finland.png",
			"France": "/Web/web-layout/data/Graphs/Import Graphs/France.png",
			"Gabon": "/Web/web-layout/data/Graphs/Import Graphs/Gabon.png",
			"Gambia": "/Web/web-layout/data/Graphs/Import Graphs/Gambia.png",
			"Georgia": "/Web/web-layout/data/Graphs/Import Graphs/Georgia.png",
			"Germany": "/Web/web-layout/data/Graphs/Import Graphs/Germany.png",
			"Ghana": "/Web/web-layout/data/Graphs/Import Graphs/Ghana.png",
			"Greece": "/Web/web-layout/data/Graphs/Import Graphs/Greece.png",
			"Guatemala": "/Web/web-layout/data/Graphs/Import Graphs/Guatemala.png",
			"Guinea": "/Web/web-layout/data/Graphs/Import Graphs/Guinea.png",
			"Guinea-Bissau": "/Web/web-layout/data/Graphs/Import Graphs/Guinea_Bissau.png",
			"Guyana": "/Web/web-layout/data/Graphs/Import Graphs/Guyana.png",
			"Haiti": "/Web/web-layout/data/Graphs/Import Graphs/Haiti.png",
			"Honduras": "/Web/web-layout/data/Graphs/Import Graphs/Honduras.png",
			"Hong Kong SAR, China": "/Web/web-layout/data/Graphs/Import Graphs/Hong_Kong_SAR_China.png",
			"Hungary": "/Web/web-layout/data/Graphs/Import Graphs/Hungary.png",
			"Iceland": "/Web/web-layout/data/Graphs/Import Graphs/Iceland.png",
			"India": "/Web/web-layout/data/Graphs/Import Graphs/India.png",
			"Indonesia": "/Web/web-layout/data/Graphs/Import Graphs/Indonesia.png",
			"Iran, Islamic Rep.": "/Web/web-layout/data/Graphs/Import Graphs/Iran_Islamic_Rep.png",
			"Iraq": "/Web/web-layout/data/Graphs/Import Graphs/Iraq.png",
			"Ireland": "/Web/web-layout/data/Graphs/Import Graphs/Ireland.png",
			"Israel": "/Web/web-layout/data/Graphs/Import Graphs/Israel.png",
			"Italy": "/Web/web-layout/data/Graphs/Import Graphs/Italy.png",
			"Côte d'Ivoire": "/Web/web-layout/data/Graphs/Import Graphs/Cote_d_Ivoire.png",
			"Jamaica": "/Web/web-layout/data/Graphs/Import Graphs/Jamaica.png",
			"Japan": "/Web/web-layout/data/Graphs/Import Graphs/Japan.png",
			"Jordan": "/Web/web-layout/data/Graphs/Import Graphs/Jordan.png",
			"Kazakhstan": "/Web/web-layout/data/Graphs/Import Graphs/Kazakhstan.png",
			"Kenya": "/Web/web-layout/data/Graphs/Import Graphs/Kenya.png",
			"Kiribati": "/Web/web-layout/data/Graphs/Import Graphs/Kiribati.png",
			"South Korea": "/Web/web-layout/data/Graphs/Import Graphs/South_Korea.png",
			"Kuwait": "/Web/web-layout/data/Graphs/Import Graphs/Kuwait.png",
			"Kyrgyzstan": "/Web/web-layout/data/Graphs/Import Graphs/Kyrgyzstan.png",
			"Laos": "/Web/web-layout/data/Graphs/Import Graphs/Laos.png",
			"Latvia": "/Web/web-layout/data/Graphs/Import Graphs/Latvia.png",
			"Lebanon": "/Web/web-layout/data/Graphs/Import Graphs/Lebanon.png",
			"Lesotho": "/Web/web-layout/data/Graphs/Import Graphs/Lesotho.png",
			"Liberia": "/Web/web-layout/data/Graphs/Import Graphs/Liberia.png",
			"Libya": "/Web/web-layout/data/Graphs/Import Graphs/Libya.png",
			"Liechtenstein": "/Web/web-layout/data/Graphs/Import Graphs/Liechtenstein.png",
			"Lithuania": "/Web/web-layout/data/Graphs/Import Graphs/Lithuania.png",
			"Luxembourg": "/Web/web-layout/data/Graphs/Import Graphs/Luxembourg.png",
			"Macao SAR, China": "/Web/web-layout/data/Graphs/Import Graphs/Macao_SAR_China.png",
			"Madagascar": "/Web/web-layout/data/Graphs/Import Graphs/Madagascar.png",
			"Malawi": "/Web/web-layout/data/Graphs/Import Graphs/Malawi.png",
			"Malaysia": "/Web/web-layout/data/Graphs/Import Graphs/Malaysia.png",
			"Maldives": "/Web/web-layout/data/Graphs/Import Graphs/Maldives.png",
			"Mali": "/Web/web-layout/data/Graphs/Import Graphs/Mali.png",
			"Malta": "/Web/web-layout/data/Graphs/Import Graphs/Malta.png",
			"Marshall Islands": "/Web/web-layout/data/Graphs/Import Graphs/Marshall_Islands.png",
			"Mauritania": "/Web/web-layout/data/Graphs/Import Graphs/Mauritania.png",
			"Mauritius": "/Web/web-layout/data/Graphs/Import Graphs/Mauritius.png",
			"Mexico": "/Web/web-layout/data/Graphs/Import Graphs/Mexico.png",
			"Micronesia": "/Web/web-layout/data/Graphs/Import Graphs/Micronesia.png",
			"Moldova": "/Web/web-layout/data/Graphs/Import Graphs/Moldova.png",
			"Monaco": "/Web/web-layout/data/Graphs/Import Graphs/Monaco.png",
			"Mongolia": "/Web/web-layout/data/Graphs/Import Graphs/Mongolia.png",
			"Montenegro": "/Web/web-layout/data/Graphs/Import Graphs/Montenegro.png",
			"Morocco": "/Web/web-layout/data/Graphs/Import Graphs/Morocco.png",
			"Mozambique": "/Web/web-layout/data/Graphs/Import Graphs/Mozambique.png",
			"Myanmar": "/Web/web-layout/data/Graphs/Import Graphs/Myanmar.png",
			"Namibia": "/Web/web-layout/data/Graphs/Import Graphs/Namibia.png",
			"Nauru": "/Web/web-layout/data/Graphs/Import Graphs/Nauru.png",
			"Nepal": "/Web/web-layout/data/Graphs/Import Graphs/Nepal.png",
			"Netherlands": "/Web/web-layout/data/Graphs/Import Graphs/Netherlands.png",
			"New Zealand": "/Web/web-layout/data/Graphs/Import Graphs/New_Zealand.png",
			"Nicaragua": "/Web/web-layout/data/Graphs/Import Graphs/Nicaragua.png",
			"Niger": "/Web/web-layout/data/Graphs/Import Graphs/Niger.png",
			"Nigeria": "/Web/web-layout/data/Graphs/Import Graphs/Nigeria.png",
			"North Macedonia": "/Web/web-layout/data/Graphs/Import Graphs/North_Macedonia.png",
			"Norway": "/Web/web-layout/data/Graphs/Import Graphs/Norway.png",
			"Oman": "/Web/web-layout/data/Graphs/Import Graphs/Oman.png",
			"Pakistan": "/Web/web-layout/data/Graphs/Import Graphs/Pakistan.png",
			"Palau": "/Web/web-layout/data/Graphs/Import Graphs/Palau.png",
			"Panama": "/Web/web-layout/data/Graphs/Import Graphs/Panama.png",
			"Papua New Guinea": "/Web/web-layout/data/Graphs/Import Graphs/Papua_New_Guinea.png",
			"Paraguay": "/Web/web-layout/data/Graphs/Import Graphs/Paraguay.png",
			"Peru": "/Web/web-layout/data/Graphs/Import Graphs/Peru.png",
			"Philippines": "/Web/web-layout/data/Graphs/Import Graphs/Philippines.png",
			"Poland": "/Web/web-layout/data/Graphs/Import Graphs/Poland.png",
			"Portugal": "/Web/web-layout/data/Graphs/Import Graphs/Portugal.png",
			"Qatar": "/Web/web-layout/data/Graphs/Import Graphs/Qatar.png",
			"Romania": "/Web/web-layout/data/Graphs/Import Graphs/Romania.png",
			"Russian Federation": "/Web/web-layout/data/Graphs/Import Graphs/Russian_Federation.png",
			"Rwanda": "/Web/web-layout/data/Graphs/Import Graphs/Rwanda.png",
			"Samoa": "/Web/web-layout/data/Graphs/Import Graphs/Samoa.png",
			"San Marino": "/Web/web-layout/data/Graphs/Import Graphs/San_Marino.png",
			"Saudi Arabia": "/Web/web-layout/data/Graphs/Import Graphs/Saudi_Arabia.png",
			"Senegal": "/Web/web-layout/data/Graphs/Import Graphs/Senegal.png",
			"Serbia": "/Web/web-layout/data/Graphs/Import Graphs/Serbia.png",
			"Seychelles": "/Web/web-layout/data/Graphs/Import Graphs/Seychelles.png",
			"Sierra Leone": "/Web/web-layout/data/Graphs/Import Graphs/Sierra_Leone.png",
			"Singapore": "/Web/web-layout/data/Graphs/Import Graphs/Singapore.png",
			"Slovakia": "/Web/web-layout/data/Graphs/Import Graphs/Slovakia.png",
			"Slovenia": "/Web/web-layout/data/Graphs/Import Graphs/Slovenia.png",
			"Solomon Islands": "/Web/web-layout/data/Graphs/Import Graphs/Solomon_Islands.png",
			"Somalia": "/Web/web-layout/data/Graphs/Import Graphs/Somalia.png",
			"South Africa": "/Web/web-layout/data/Graphs/Import Graphs/South_Africa.png",
			"South Sudan": "/Web/web-layout/data/Graphs/Import Graphs/South_Sudan.png",
			"Spain": "/Web/web-layout/data/Graphs/Import Graphs/Spain.png",
			"Sri Lanka": "/Web/web-layout/data/Graphs/Import Graphs/Sri_Lanka.png",
			"St. Kitts and Nevis": "/Web/web-layout/data/Graphs/Import Graphs/St_Kitts_and_Nevis.png",
			"St. Lucia": "/Web/web-layout/data/Graphs/Import Graphs/St_Lucia.png",
			"St. Vincent and the Grenadines": "/Web/web-layout/data/Graphs/Import Graphs/St_Vincent_and_the_Grenadines.png",
			"Sudan": "/Web/web-layout/data/Graphs/Import Graphs/Sudan.png",
			"Suriname": "/Web/web-layout/data/Graphs/Import Graphs/Suriname.png",
			"Sweden": "/Web/web-layout/data/Graphs/Import Graphs/Sweden.png",
			"Switzerland": "/Web/web-layout/data/Graphs/Import Graphs/Switzerland.png",
			"Syrian Arab Republic": "/Web/web-layout/data/Graphs/Import Graphs/Syrian_Arab_Republic.png",
			"Tajikistan": "/Web/web-layout/data/Graphs/Import Graphs/Tajikistan.png",
			"Tanzania": "/Web/web-layout/data/Graphs/Import Graphs/Tanzania.png",
			"Thailand": "/Web/web-layout/data/Graphs/Import Graphs/Thailand.png",
			"East Timor": "/Web/web-layout/data/Graphs/Import Graphs/East_Timor.png",
			"Togo": "/Web/web-layout/data/Graphs/Import Graphs/Togo.png",
			"Tonga": "/Web/web-layout/data/Graphs/Import Graphs/Tonga.png",
			"Trinidad and Tobago": "/Web/web-layout/data/Graphs/Import Graphs/Trinidad_and_Tobago.png",
			"Tunisia": "/Web/web-layout/data/Graphs/Import Graphs/Tunisia.png",
			"Turkey": "/Web/web-layout/data/Graphs/Import Graphs/Turkey.png",
			"Turkmenistan": "/Web/web-layout/data/Graphs/Import Graphs/Turkmenistan.png",
			"Tuvalu": "/Web/web-layout/data/Graphs/Import Graphs/Tuvalu.png",
			"Uganda": "/Web/web-layout/data/Graphs/Import Graphs/Uganda.png",
			"Ukraine": "/Web/web-layout/data/Graphs/Import Graphs/Ukraine.png",
			"United Arab Emirates": "/Web/web-layout/data/Graphs/Import Graphs/United_Arab_Emirates.png",
			"United Kingdom": "/Web/web-layout/data/Graphs/Import Graphs/United_Kingdom.png",
			"United States": "/Web/web-layout/data/Graphs/Import Graphs/United_States.png",
			"Uruguay": "/Web/web-layout/data/Graphs/Import Graphs/Uruguay.png",
			"Uzbekistan": "/Web/web-layout/data/Graphs/Import Graphs/Uzbekistan.png",
			"Vanuatu": "/Web/web-layout/data/Graphs/Import Graphs/Vanuatu.png",
			"Venezuela, RB": "/Web/web-layout/data/Graphs/Import Graphs/Venezuela_RB.png",
			"Vietnam": "/Web/web-layout/data/Graphs/Import Graphs/Vietnam.png",
			"Yemen, Rep.": "/Web/web-layout/data/Graphs/Import Graphs/Yemen_Rep.png",
			"Zambia": "/Web/web-layout/data/Graphs/Import Graphs/Zambia.png",
			"Zimbabwe": "/Web/web-layout/data/Graphs/Import Graphs/Zimbabwe.png"
		},
        top20: {
			"Category 2": "/Web/web-layout/data/Graphs/Top 20 Countries by Categories/Top 20 Arms Importing Countries by Category 2.png",
			"Category 4": "/Web/web-layout/data/Graphs/Top 20 Countries by Categories/Top 20 Arms Importing Countries by Category 4.png",
			"Category 6": "/Web/web-layout/data/Graphs/Top 20 Countries by Categories/Top 20 Arms Importing Countries by Category 6.png",
			"Category 7": "/Web/web-layout/data/Graphs/Top 20 Countries by Categories/Top 20 Arms Importing Countries by Category 7.png",
			"Category 8": "/Web/web-layout/data/Graphs/Top 20 Countries by Categories/Top 20 Arms Importing Countries by Category 8.png",
			"Category 9": "/Web/web-layout/data/Graphs/Top 20 Countries by Categories/Top 20 Arms Importing Countries by Category 9.png",
			"Category 20": "/Web/web-layout/data/Graphs/Top 20 Countries by Categories/Top 20 Arms Importing Countries by Category 20.png"
		}		
    };

    function resetToDefault() {
        countrySelector.innerHTML = '<option value="" selected disabled>Country/Category</option>';
        imageContainer.innerHTML = '<p>Please select a chart type and country/category.</p>';
    }

    chartTypeSelector.addEventListener('change', () => {
        const selectedChart = chartTypeSelector.value;
        resetToDefault();
        if (chartData[selectedChart]) {
            chartData[selectedChart].forEach(item => {
                const option = document.createElement('option');
                option.value = item;
                option.textContent = item;
                countrySelector.appendChild(option);
            });
        }
    });

    countrySelector.addEventListener('change', () => {
        const selectedChart = chartTypeSelector.value;
        const selectedCategory = countrySelector.value;
        if (imageMapping[selectedChart] && imageMapping[selectedChart][selectedCategory]) {
            const imagePath = imageMapping[selectedChart][selectedCategory];
            imageContainer.innerHTML = `<img src="${imagePath}" alt="${selectedCategory}" style="max-width: 100%; height: auto; border: 1px solid #ddd; border-radius: 5px;">`;
        } else {
            imageContainer.innerHTML = '<p style="color: red;">No image available for this category.</p>';
        }
    });
});